require: 
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/support/**/*'
    - 'spec/*_helper.rb'
    - 'bin/{rails,rake}'
Layout/LineLength:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - 'spec/**/*'
    - 'app/admin/**/*'
    - '**/*.rake'
RSpec/EmptyLineAfterSubject:
  Exclude:
    - 'spec/factories.rb'
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
RSpec/ExampleWording:
  Enabled: false
RSpec/ImplicitExpect:
  EnforcedStyle: should
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/ReturnFromStub:
  EnforcedStyle: block
Style/Documentation:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Semicolon:
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true